# Generated by Django 4.2.2 on 2023-06-22 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default='', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
