# Generated by Django 4.2.2 on 2023-06-19 16:16

import cibies_store.user_profile.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(2), cibies_store.user_profile.validators.alphanumeric_charcters_validator, cibies_store.user_profile.validators.first_letter_uppercase_validator])),
                ('last_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(2), cibies_store.user_profile.validators.alphanumeric_charcters_validator, cibies_store.user_profile.validators.first_letter_uppercase_validator])),
                ('email', models.EmailField(max_length=40)),
                ('password', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(6)])),
                ('image_url', models.URLField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(16)])),
            ],
        ),
    ]
